### ISSUE TITLE
AvatarWithRoundedCorner not transparent

### ISSUE THREAD

**Issue by thhet** [SixLabors/Samples#10]
It seems, that the rounded corner sample is not working well with photo images. The cut out corners are not transparent for a lot of images. Cliparts are usually ok, but real world images tend to produce black corners.

![sprinkles](https://user-images.githubusercontent.com/25905746/61804603-7bcbd880-ae34-11e9-96c4-fa808c8762fb.png)

![fb-round](https://user-images.githubusercontent.com/25905746/61804749-c4839180-ae34-11e9-8b41-8080d4cbad87.png)

**Comment by JimBobSquarePants** [comment]
I’m assuming from the output these images are jpegs?

If so, that’s expected as jpegs do not contain an alpha channel.

**Comment by thhet** [comment]
Input image is a png. But your comment has led me to a solution: When I serialize the selected image into a memory stream using a PngEncoder with ColorType = PngColorType.RgbWithAlpha, load the image from this stream and than apply rounded corners everything works as expected. 

Thanks for your reply!

**Comment by JimBobSquarePants** [comment]
Excellent! Glad you worked it out 👍
