### ISSUE TITLE
Crop image sample

### ISSUE THREAD

**Issue by Fabioh** [SixLabors/Samples#2]
- Is there a sample of how to crop an image file to generate thumbnail?

**Comment by JimBobSquarePants** [comment]
No but the API docs should cover you well here.

https://sixlabors.github.io/docs/api/ImageSharp/SixLabors.ImageSharp.Processing.Transforms.CropExtensions.html

Often I've seen Resize/Crop used interchangeably so here's the link to resize also.

https://sixlabors.github.io/docs/api/ImageSharp/SixLabors.ImageSharp.Processing.Transforms.ResizeExtensions.html

Remember, these are all extension methods so you would use them thus.

``` c#
// Act on given image
image.Mutate(x => x.Crop(...))

image.Mutate(x => x.Resize(...))

// Create clone and act on that.
var image2 = image.Clone(x => x.Crop(...))

var image2 = image.Clone(x => x.Resize(...))

```

I hope that helps.

We'll be doing a lot of work to flesh out the documentation with examples for common operations.

Cheers

James
