### ISSUE TITLE
Fonts package referenced in sample projects is outdated

### ISSUE THREAD

**Issue by enriko-riba** [SixLabors/Samples#20]
The projects are still referencing beta 19 of Fonts packages. 
Further issue is that upgrading to Fonts v1.0.0. breaks some samples e.g. 
`Method not found: 'Void SixLabors.Fonts.IGlyphRenderer.BeginText(SixLabors.Fonts.FontRectangle)'.` in DrawingTextAlongAPath

**Comment by JimBobSquarePants** [comment]
Feel free to open a PR to update them

**Comment by enriko-riba** [comment]
Updating is easy, the real issue are breaking changes causing exceptions

**Comment by JimBobSquarePants** [comment]
Gimme a week. I’ll get Drawing V1 done

**Comment by enriko-riba** [comment]
@JimBobSquarePants seems its working with Drawing 1.0.0-beta15.14 + minor breaking change fixes like TextMeasurer.Measure -> TextMeasurer.MeasureAdvance and TextOptions -> RichTextOptions.
Although technically not needed I had to upgrade .NET framework to 7.0.

Wanted to create a PR with fixes but have no permissions to push new branches into the repo.
