### ISSUE TITLE
How to generate Complimentary color sets on the Colorwheel

### ISSUE THREAD

**Issue by ridingmower** [SixLabors/Samples#28]
Hello, I am trying to test cases. I am new to the color math

- [ ] Is there a function to generate 3 or 4 complimentary colors on the color wheel
- [ ] Is there a function to generate color schemes/sets that ADA compliant

**Comment by JimBobSquarePants** [comment]
Hi @ridingmower There are no built-in methods in the Six Labors libraries that support these operations.
