### ISSUE TITLE
Drawing text sample outdated

### ISSUE THREAD

**Issue by 2E0PGS** [SixLabors/Samples#8]
The following is outdated it now takes `PointF` instead of `IPath`.

https://github.com/SixLabors/Samples/blob/b776ea0a133e3930169dfbf5302c1bfbd57311f6/ImageSharp/DrawingTextAlongAPath/Program.cs#L46

It would look like this now:

```csharp
PointF pointF = new PointF(60, 170);

image.Mutate(x => x.DrawText("My text here", font, Rgba32.Blue, pointF));
```

**Comment by JimBobSquarePants** [comment]
Thanks. See #7 for update.
